In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
b = np.array([[1.2, 5.4, 7.1], [3.2, 2.3, 1.3]])

In [4]:
print(a)

[1 2 3]


In [5]:
print(b)

[[1.2 5.4 7.1]
 [3.2 2.3 1.3]]


In [6]:
#get dimension

In [7]:
print(f"a-array dimension: {a.ndim}, b-array dimension: {b.ndim}")

a-array dimension: 1, b-array dimension: 2


In [8]:
#get shape

In [9]:
print(f"a-array shape: {a.shape}, b-array shape: {b.shape}")

a-array shape: (3,), b-array shape: (2, 3)


In [10]:
# get type and size

In [11]:
print(a.dtype)

int32


In [12]:
a = np.array([1, 2, 3], dtype='int8')

In [13]:
print(a.dtype)

int8


In [16]:
# get size (number of elements)

In [15]:
print(a.size)

3


In [17]:
# access elements

In [18]:
print(a)

[1 2 3]


In [19]:
print(b)

[[1.2 5.4 7.1]
 [3.2 2.3 1.3]]


In [20]:
print(b[1, 2])
print(b[1][2])

1.3
1.3


In [24]:
# get last element from every row

In [23]:
print(b[:, -1])

[7.1 1.3]


In [25]:
# get specific row

In [22]:
print(b[0, :]) 

[1.2 5.4 7.1]


In [27]:
b[0, 2] = 3.14 

In [28]:
print(b)

[[1.2  5.4  3.14]
 [3.2  2.3  1.3 ]]


In [30]:
# initialize all zeros matrix
np.zeros((2, 3)) # shape inside brackets

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# initialize all ones matrix
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
# intialize matrix with specific number 
np.full((2, 2), 0.99)

array([[0.99, 0.99],
       [0.99, 0.99]])

In [34]:
# initialize matrix with random numbers
np.random.rand(4, 2) # not a tupple with shapes, nut rows, columns..

array([[0.13186746, 0.85689512],
       [0.79053316, 0.95254777],
       [0.23242439, 0.44211402],
       [0.73311145, 0.75289983]])

In [36]:
np.random.randint(low=4, high=10, size=(2, 2))

array([[8, 6],
       [7, 8]])

In [37]:
# identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# repeat an array
arr = np.array([1, 2, 7])
repeated = np.repeat(arr, repeats=3, axis=0)
print(repeated)

[1 1 1 2 2 2 7 7 7]


In [41]:
arr = np.array([[1, 2, 7]])
repeated = np.repeat(arr, repeats=3, axis=0)
print(repeated)

[[1 2 7]
 [1 2 7]
 [1 2 7]]


In [44]:
arr = np.array([[1, 2, 7]])
repeated = np.repeat(arr, repeats=3)
print(repeated)

[1 1 1 2 2 2 7 7 7]


In [45]:
# Mathematics

In [46]:
a = np.array([1, 2, 3, 4])

In [47]:
a - 2

array([-1,  0,  1,  2])

In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a * 2

array([2, 4, 6, 8])

In [50]:
b = np.array([0, -10, 2, 40])

In [51]:
a * b

array([  0, -20,   6, 160])

In [52]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
# Linear algebra

In [54]:
a = np.ones((2, 3))
b = np.full((3, 2), 5)

In [55]:
np.matmul(a, b)

array([[15., 15.],
       [15., 15.]])

In [56]:
# statistics

In [57]:
rand = np.random.rand(4, 2)

In [58]:
print(rand)

[[0.69270919 0.20432018]
 [0.82594834 0.93719061]
 [0.81889776 0.16898289]
 [0.5499406  0.87394656]]


In [59]:
np.min(rand, axis=0)

array([0.5499406 , 0.16898289])

In [60]:
np.min(rand, axis=1)

array([0.20432018, 0.82594834, 0.16898289, 0.5499406 ])

In [61]:
np.sum(rand, axis=0)

array([2.88749588, 2.18444024])

In [62]:
# reorganizing arrays

In [63]:
before = np.array([[1, 2, 3, 4], [3, 7, 8, 9]])
print(before)

[[1 2 3 4]
 [3 7 8 9]]


In [64]:
after = before.reshape(8, 1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [3]
 [7]
 [8]
 [9]]
